export const RouterPath = {
    HOME: '/home',
    SEARCH: '/search',
    CONFIRM_INFORMATION: '/confirm-information',
    CREATED_SUCCESS: '/created_success',
    DETAIL: '/detail',
    REGISTER_HOST: '/register-host',
    ADMIN: '/admin',
    PROFILE: '/profile',
    MY_TICKET: '/my-ticket',
    MY_WALLET: '/my-wallet',
    CHANGE_PASSWORD: '/change-password',
    VNPAY_RETURN: '/vnpay/return',
    NOT_FOUND: '/*',
};
