export default class Constants {
  static optionsStatusBooking = [
    { label: 'Chưa xác nhận', value: 1 },
    { label: 'Đã xác nhận', value: 2 },
    { label: 'Đã khám', value: 3 },
    { label: 'BS Đã đánh giá', value: 4 },
    // { label: "BN Đã đánh giá", value: 5 },
  ];
  static vietnamProvinces = [
    { label: 'Hà Nội', value: 1 },
    { label: 'Hà Giang', value: 2 },
    { label: 'Cao Bằng', value: 3 },
    { label: 'Lào Cai', value: 4 },
    { label: 'Điện Biên', value: 5 },
    { label: 'Lai Châu', value: 6 },
    { label: 'Sơn La', value: 7 },
    { label: 'Yên Bái', value: 8 },
    { label: 'Tuyên Quang', value: 9 },
    { label: 'Lạng Sơn', value: 10 },
    { label: 'Quảng Ninh', value: 11 },
    { label: 'Hòa Bình', value: 12 },
    { label: 'Ninh Bình', value: 13 },
    { label: 'Thái Bình', value: 14 },
    { label: 'Thanh Hóa', value: 15 },
    { label: 'Nghệ An', value: 16 },
    { label: 'Hà Tĩnh', value: 17 },
    { label: 'Quảng Bình', value: 18 },
    { label: 'Quảng Trị', value: 19 },
    { label: 'Thừa Thiên-Huế', value: 20 },
    { label: 'Đà Nẵng', value: 21 },
    { label: 'Quảng Nam', value: 22 },
    { label: 'Quảng Ngãi', value: 23 },
    { label: 'Bình Định', value: 24 },
    { label: 'Phú Yên', value: 25 },
    { label: 'Khánh Hòa', value: 26 },
    { label: 'Ninh Thuận', value: 27 },
    { label: 'Bình Thuận', value: 28 },
    { label: 'Kon Tum', value: 29 },
    { label: 'Gia Lai', value: 30 },
    { label: 'Đắk Lắk', value: 31 },
    { label: 'Đắk Nông', value: 32 },
    { label: 'Lâm Đồng', value: 33 },
    { label: 'Bình Phước', value: 34 },
    { label: 'Tây Ninh', value: 35 },
    { label: 'Bình Dương', value: 36 },
    { label: 'Đồng Nai', value: 37 },
    { label: 'Bà Rịa-Vũng Tàu', value: 38 },
    { label: 'Hồ Chí Minh', value: 39 },
    { label: 'Long An', value: 40 },
    { label: 'Tiền Giang', value: 41 },
    { label: 'Bến Tre', value: 42 },
    { label: 'Trà Vinh', value: 43 },
    { label: 'Vĩnh Long', value: 44 },
    { label: 'Đồng Tháp', value: 45 },
    { label: 'An Giang', value: 46 },
    { label: 'Kiên Giang', value: 47 },
    { label: 'Cần Thơ', value: 48 },
    { label: 'Hậu Giang', value: 49 },
    { label: 'Sóc Trăng', value: 50 },
    { label: 'Bạc Liêu', value: 51 },
    { label: 'Cà Mau', value: 52 },
    { label: 'Tây Ninh', value: 53 },
    { label: 'Cộng Hòa Xã Hội Chủ Nghĩa Việt Nam', value: 54 },
    { label: 'Hà Giang', value: 55 },
    { label: 'Cao Bằng', value: 56 },
    { label: 'Lào Cai', value: 57 },
    { label: 'Điện Biên', value: 58 },
    { label: 'Lai Châu', value: 59 },
    { label: 'Sơn La', value: 60 },
    { label: 'Yên Bái', value: 61 },
    { label: 'Tuyên Quang', value: 62 },
    { label: 'Lạng Sơn', value: 63 },
  ];
}

export const BUSES_LIST = [
  {
    id: 1,
    label: '40-Seater Sleeper Bus',
    name: 'Xe Giường Nằm 40 Chỗ',
    seats: 40,
    rowsPerLevel: 5, // Số hàng mỗi tầng
    seatsPerRow: 3,
    levels: 2, // Xe 2 tầng
    lastRowSeats: 5,
  },
  {
    id: 2,
    label: '46-Seater Sleeper Bus',
    name: 'Xe Giường Nằm 46 Chỗ',
    seats: 46,
    seatsPerRow: 3,
    levels: 2,
    rowsPerLevel: 6,
    lastRowSeats: 5,
  },
  {
    id: 4,
    label: '29-Seater Coach',
    name: 'Xe Khách 32 Chỗ',
    seats: 32,
    rowsPerLevel: 4,
    seatsPerRow: 3,
    levels: 2,
    lastRowSeats: 4,
  },
  {
    id: 5,
    label: '34-Seater Coach',
    name: 'Xe Khách 34 Chỗ',
    seats: 34,
    rowsPerLevel: 5,
    seatsPerRow: 3,
    levels: 2,
    lastRowSeats: 2,
  },

  {
    id: 3,
    label: '9-Seater Limousine',
    name: 'Xe Limousine 20 giường',
    seats: 20,
    rowsPerLevel: 5,
    seatsPerRow: 2,
    levels: 2,
    lastRowSeats: 0,
  },
  {
    id: 6,
    label: '45-Seater Coach',
    name: 'Xe Khách 44 Chỗ',
    seats: 44,
    rowsPerLevel: 10,
    seatsPerRow: 4,
    levels: 1,
    lastRowSeats: 5,
  },
  {
    id: 7,
    label: 'VIP Sleeper Bus',
    name: 'Xe Giường Nằm VIP',
    seats: 40,
    rowsPerLevel: 5,
    seatsPerRow: 4,
    levels: 2,
    lastRowSeats: 4,
  },
  {
    id: 8,
    label: '16-Seater Van',
    name: 'Xe Du Lịch 16 Chỗ',
    seats: 16,
    rowsPerLevel: 4,
    seatsPerRow: 4,
    levels: 1,
    lastRowSeats: 4,
  },
  {
    id: 9,
    label: '30-Seater Tour Bus',
    name: 'Xe Du Lịch 30 Chỗ',
    seats: 30,
    rowsPerLevel: 8,
    seatsPerRow: 4,
    levels: 1,
    lastRowSeats: 2,
  },
  {
    id: 10,
    label: 'Long-Distance Bus',
    name: 'Xe Buýt Đường Dài',
    seats: 50,
    rowsPerLevel: 6,
    seatsPerRow: 5,
    levels: 2,
    lastRowSeats: 6,
  },
];

export const FEATURE = [
  {
    id: 'F1',
    name: 'Không cần thanh toán trước',
    icon: 'fa fa-credit-card text-green-500',
  },
  {
    id: 'F2',
    name: 'Có trung chuyển đón/trả',
    icon: 'fa fa-shuttle-van text-blue-500',
  },
  {
    id: 'F3',
    name: 'Được chọn chỗ ngồi',
    icon: 'fa fa-chair text-purple-500',
  },
  {
    id: 'F4',
    name: 'Chăn đắp',
    icon: 'fa fa-bed text-yellow-500',
  },
  {
    id: 'F5',
    name: 'Wifi',
    icon: 'fa fa-wifi text-blue-500',
  },
  {
    id: 'F6',
    name: 'Điều hòa',
    icon: 'fa fa-snowflake text-cyan-500',
  },
  {
    id: 'F7',
    name: 'Phục vụ nước miễn phí',
    icon: 'fas  fa-tint text-blue-500',
  },
  {
    id: 'F8',
    name: 'Xuất ăn miễn phí',
    icon: 'fa fa-utensils text-red-500',
  },
  {
    id: 'F9',
    name: 'Nghỉ giữa chuyến',
    icon: 'fa fa-stopwatch text-orange-500',
  },
  {
    id: 'F10',
    name: 'Cho phép mang thú cưng',
    icon: 'fa fa-paw text-brown-500',
  },
  {
    id: 'F11',
    name: 'Búa phá kính',
    icon: 'fa fa-hammer text-gray-500',
  },
];

export const ROLES = Object.freeze({
  ADMIN: 'admin',
  BUS_OWNER: 'busOwner',
  TICKET_CONTROLLER: 'ticketController',
  USER: 'user',
});

export const sidebarItems = [
  {
    id: 'dashboardAll',
    icon: 'fa-th-large',
    label: 'Tổng quan',
    roles: ['admin'],
  },
  {
    id: 'busAll',
    icon: 'fa-bus',
    label: 'Danh sách chuyến xe',
    roles: ['admin'],
  },
  {
    id: 'usersAll',
    icon: 'fa-users',
    label: 'Danh sách tài khoản',
    active: true,
    roles: ['admin'],
  },
  {
    id: 'ticketAll',
    icon: 'fa-tasks',
    label: 'Danh sách vé xe',
    active: true,
    roles: ['admin'],
  },
  {
    id: 'request',
    icon: 'fa-clipboard-list',
    label: 'Đăng ký nhà xe mới',
    roles: ['admin'],
  },
  {
    id: 'dashboard',
    icon: 'fa-th-large',
    label: 'Tổng quan',
    roles: ['chuNhaXe'],
  },
  {
    id: 'users',
    icon: 'fa-users',
    label: 'Danh sách tài khoản',
    active: true,
    roles: ['chuNhaXe'],
  },
  {
    id: 'buses',
    icon: 'fa-bus',
    label: 'Danh sách chuyến xe',
    roles: ['chuNhaXe', 'taiXe', 'phuXe'],
  },
  {
    id: 'tickets',
    icon: 'fa-clipboard-list',
    label: 'Danh sách vé xe',
    roles: ['chuNhaXe', 'nhanVien'],
  },
  {
    id: 'profile',
    icon: 'fa-smile',
    label: 'Thông tin tài khoản',
    roles: ['chuNhaXe', 'nhanVien', 'taiXe', 'phuXe'],
  },
];
